### ISSUE TITLE
Map stays attached to player after exiting vehicle

### ISSUE THREAD

**Issue by ghost** [LAxemann/RR_mapStuff#5]
1. Description:
After some magic like opening map in vehicle, or entering vehicle with open map, it stays attached to player's hand and covers more than half of the screen, prevents shooting from hip, scopes and binoculars are working normally.

2. Steps to Reproduce
Not quite sure, but something with entering or/and exiting vehicle, while holding or using map.

3. Environment Setup and Configuration
Issue was seen on dedicated server(Verify signatures: v2), happend only  to one player with 12-15 connected.

4. Media
https://imgur.com/a/7yNWSkF

**Comment by Dystopian** [comment]
Repro: start entering a vehicle, then quickly open map while entering (while is not in vehicle yet). Exit vehicle - map is attached to player.
Maybe should add CBA `vehicle` EH with `CBA_fnc_addPlayerEventHandler` to handle this bug.

**Comment by Dystopian** [comment]
To fix bug during mission run this in console (local exec):
```
false call RR_mapStuff_fnc_mapEH;
{detach _x; deleteVehicle _x} forEach attachedObjects player;
```

**Comment by LAxemann** [comment]
Should be fixed! :)
