### ISSUE TITLE
Looking at dead body's map will create map item in players inventory when not having 

### ISSUE THREAD

**Issue by OverlordZorn** [LAxemann/RR_mapStuff#6]
When the Player does not have a map and he looks at the map of a dead body, it will create a map in his inventory while the body's map remains in the inventory.

Edit:

oh god i did a mistake, remove this issue i made the report before i double checked everything im sorry please delete! i dont speak github enough to know how!

**Comment by LAxemann** [comment]
No worries dude, glad it seems to work! :)
