### ISSUE TITLE
Opening the map during the reload of certain weapons breaks the reload

### ISSUE THREAD

**Issue by godonan** [LAxemann/RR_mapStuff#9]
**Description:**
Opening the map during the reload of certain weapons (particularly belt-fed MGs) interrupts the reload process, breaks the animation, and consumes a box from the inventory.

**Reproduction:**
Using an LMG, initiate a reload, then open the map.

**Demonstration:**

https://user-images.githubusercontent.com/83740572/117356166-4e64e900-ae68-11eb-9d6f-809ae210fa0d.mp4

**Comment by godonan** [comment]
Reload interruption also occurs when reloading underbarrel grenade launcher. This interruption also occurs for some weapon magazines (tested on MX 3GL and P99).

It should be noted that no such interruption occurs when reloading the vanilla RPG-32 launcher or the Titan MRPL. The interruption occurs when reloading the CUP RPG-7V2 launcher.

**Comment by LAxemann** [comment]
Thanks for the report! Took a while, but fixed now. The map can be opened as usualy during reloads, but the actual mod functionality and animations will only kick in once the reload is done. :)
